### ISSUE TITLE
2010-A8 Failure to Restrict URL Access

### ISSUE THREAD

**Issue by s1155033765** [ierg4210/shop39#3]
Can directly get into /checkout/thankyou and /checkout/error without any account checking

http://i218.photobucket.com/albums/cc176/William_AOE/IERG4210/store39%20checkout%20direct%20thankyou.png

http://i218.photobucket.com/albums/cc176/William_AOE/IERG4210/store39%20checkout%20direct%20error.png

**Comment by s1155035406** [comment]
phase 5 was not yet finish
