### ISSUE TITLE
Potential MITM attack

### ISSUE THREAD

**Issue by s1155015942** [ierg4210/shop39#5]
Detailed steps to reproduce? When a victim use http req, not https req to log in to your admin page, his/her password can be viewed in plaintext though MITM attack.
What did you see? People can access your admin page in HTTP
What did you expect to see? When I use HTTP to access your admin page, it will redirect to HTTPS
What is the possible fix? Add Strict-Transport-Security header or redirect it in server side:
app.use('/admin', function(req, res, next) {
var schema = req.headers['x-forwarded-proto'];
if (schema === 'https') {
// Already https; don't do anything special.
next();
}
else {
// Redirect to https.
res.redirect('https://' + req.headers.host + req.url + '/admin');
}
});

![-2](https://cloud.githubusercontent.com/assets/10694550/7541720/f721b46c-f5e9-11e4-9a7d-0e5ecb4792e2.jpg)

**Comment by s1155035406** [comment]
being commented due to testing in localhost
